# This compose file only deploys and configures minio.
# If you are looking to host the static frontend site, refer frontend/docker-compose.yml

services:
    minio:
        image: minio/minio
        ports:
            - ${MINIO_PORT}:9000
        command: server /data
        volumes:
            - ${BALTI_PATH}/minio-data:/data
            # - minio-data:/data # You can use volumes instead of bind mounts

    minio-provision:
        image: minio/mc
        depends_on:
            - minio
        volumes:
            - ${BALTI_PATH}/minio-provision.sh:/minio-provision.sh:ro
            - ${BALTI_PATH}/lifecycle_expiry.json:/lifecycle_expiry.json:ro
            - ${BALTI_PATH}/bucket_policy.json:/bucket_policy.json:ro
            - ${BALTI_PATH}/minio-data:/data
        entrypoint: sh /minio-provision.sh
# You can use volumes instead of bind mounts
#volumes:
#    minio-data:
